### ISSUE TITLE
No such method exception

### ISSUE THREAD

**Issue by brucieW** [jfree/jfreechart#94]
I am trying to migrate to 1.5.0. I have a class that extends XYDrawableAnnotation.  I have no compile issues. When I call the super class in my constructor, I get a NoSuchMethodException.

public class BaseTradeMarker extends XYDrawableAnnotation {
....
	public BaseTradeMarker(ITrade trade, double x, double y, Drawable drawable)
	{
		super(x, y, displayWidth, displayHeight, drawable);

Exception in thread "Thread-2" java.lang.NoSuchMethodError: org.jfree.chart.annotations.XYDrawableAnnotation.<init>(DDDDLorg/jfree/chart/ui/Drawable;)V
	at charts.common.BaseTradeMarker.<init>(BaseTradeMarker.java:101)

Is there something I have to do to get my old code working with 1.5?

Thanks in advance.
