### ISSUE TITLE
`org.jfree.chart.ChartUtilities` renamed to `org.jfree.chart.ChartUtils` without deprecated paper-trail

### ISSUE THREAD

**Issue by ronreynolds2** [jfree/jfreechart#66]
more of a comment; tho also the javadocs don't mention this move (in fact Google has yet to hear of org.jfree.chart.ChartUtils; it was only by cracking open the 1.5.0 jar that we were able to find where ChartUtilities went).

**Comment by mayuso** [comment]
Same happened with `org.jfree.chart.util.ParamChecks`. It's named `org.jfree.chart.util.Args` now.

**Comment by tomas-pluskal** [comment]
Also many getBase/setBase methods were renamed to getDefault/setDefault (e.g., XYLineAndShapeRenderer.setBaseLinesVisible() -> XYLineAndShapeRenderer.setDefaultLinesVisible(). I had to correct about 200 compilation errors in my project after upgrading JFreeChart from 1.0.19 to 1.5.0. That's life, I guess. But wasn't the https://github.com/jfree/jfreechart-fse project started for that purpose (updating the API)?

**Comment by jfree** [comment]
Please list all the changes you spot, I'll add migration notes to the README.  And I'll get the latest API docs uploaded and update the website.

**Comment by krheinwald** [comment]
This is what noted when ported my application from jfreechart 1.10.19:

- org.jfree.ui became org.jfree.chart.ui

- (Stacked)BarRenderer3D
- Axis3D
- setToolTipGenerator()
- org.jfree.ui.about

disapperead? These changes impact my exisitng functionality.

**Comment by Petikoch** [comment]
org.jfree.ui.RefineryUtilities -> org.jfree.chart.ui.UIUtils

**Comment by Petikoch** [comment]
`import org.jfree.ui. ...` -> `import org.jfree.chart.ui. ...`

**Comment by Petikoch** [comment]
But most important: The 1.5.0 charts looks as good as the 1.0.19 charts -> everything is working fine after the manuel code migration :-) Thank you @jfree for this library!

**Comment by krheinwald** [comment]
@Petikoch - Did you use any of 3D Bar Charts, Custom Tooltips, Context Menus? It seems they went AWOL?

**Comment by Petikoch** [comment]
@krheinwald I don’t know, I’m using only 2D stuff

**Comment by krheinwald** [comment]
Thanks! Any experience with the other sstuff -Tooltips, Context Menus?

**Comment by jfree** [comment]
> On 16 Nov 2017, at 13:00, krheinwald <notifications@github.com> wrote:
> 
> This is what noted when ported my application from jfreechart 1.10.19:
> 
> org.jfree.ui became org.jfree.chart.ui
> 
> (Stacked)BarRenderer3D
> 
> 
> Axis3D
> 


The “faux” 3D plot code is removed, better options are provided by Orson Charts.

> 
> setToolTipGenerator()
> 
> 
Should be still there…getDefaultToolTipGenerator()?
> 
> org.jfree.ui.about
> 
> disapperead? These changes impact my exisitng functionality.
> 
> 

This stuff wasn’t really essential, but please copy the classes from JCommon if you need them.

I added some notes to the README for the 3D classes.

**Comment by bourgesl** [comment]
I successfully migrated to JFreeChart 1.5, only lots of (painful but) trivial class name changes / fix imports.

One question: 
I just figured out the (default) legend has no more a visible border, is it wanted ?
You can see it in jfreechart demos v1.0.19 but no more in v1.5

Will see if there are new legend properties...

**Comment by twistedtwin** [comment]
DatasetUtilities moved to DatasetUtils

**Comment by twistedtwin** [comment]
ShapeUtilities renamed to ShapeUtils
TextUtilities renamed to TextUtils

isPointInRect moved from AbstractXYItemRenderer to ShapeUtils

**Comment by pos9101** [comment]
I had used custom calculateDomainMarkerTextAnchorPoint() in CombinedDomainXYPlot. 
I change method from RectangleAnchor.coordinates(Rectangle2D anchorRect. RectangleAnchor anchor) to anchor.getAnchorPoint(RectangleAnchor anchorRect). 

RectangleAnchor.coordinates disappear.

**Comment by trashgod** [comment]
I see that change [here](7674b090ffd46b2d6c8b5c332c5f09a8880ee1ee) in the v1.5.3 branch. The changes may guide your revised approach.

**Comment by trashgod** [comment]
See also [_Migration_](https://github.com/jfree/jfreechart#migration).

**Comment by ffedeli** [comment]
Right clicking a chart and selecting "save as ... png" I got this error msg : "java.lang.NoClassDefFoundError: org/jfree/chart/ChartUtilities". (Jfreechart vers. 1.5.4, maven dependency)

**Comment by trashgod** [comment]
> Right clicking a chart and selecting "save as ... png" I got this error msg : "java.lang.NoClassDefFoundError: org/jfree/chart/ChartUtilities". (Jfreechart vers. 1.5.4, maven dependency)

I can't reproduce this  using `jfreechart-1.5.4` from [here](https://repo1.maven.org/maven2/org/jfree/jfreechart/1.5.4/), which uses `org.jfree.chart.ChartUtils`. Any chance you have an older version in the classpath?

**Comment by ffedeli** [comment]
Probably this issue comes from this MAVEN dependency I used: 

<dependency>
    <groupId>org.jfree</groupId>
    <artifactId>jfreechart</artifactId>
    <version>1.5.4</version>
</dependency>

In fact, replacing this dependency with your jfreechart-1.5.4.jar file directly in my java build path all runs OK.

Note: I compared with Windows FC command your jfreechart-1.5.4.jar file with my maven downloaded file and they seem identical, so I don't understand why the second solution works fine

Thank you for your support

**Comment by ffedeli** [comment]
Sorry, this is MAVEN dependency link https://mvnrepository.com/artifact/org.jfree/jfreechart

**Comment by trashgod** [comment]
Yes, the files have identical checksums.  Did any older version(s) turn up on the classpath? Youmight search for errant JARs in the directories found in the system property `java.library.path` or your IDE's project library.

**Comment by ffedeli** [comment]
Found, it's my fault. My Java application is designed in the SWT framework, so I thought I should use both MAVEN dependencies for jfreechart-1.5.4.jar and jfreechart-swt-1.0.jar. It was a big mistake, only the latter is necessary!!
In fact, jfreechart-swt-1.0.jar has embedded jfreechart-1.0.19.jar (and other jars...) as you can see in the attached file
By doing so everything really works well!!
Your last comment, **trashgod**, put me on the right track, thanks

**Comment by ffedeli** [comment]
sorry, this is the file
![Screenshot 2024-04-25 170308](https://github.com/jfree/jfreechart/assets/34574583/39ac1e6b-2c1b-48d6-bf02-bc3976f832f4)
